//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto2Entities : DbContext
    {
        public Proyecto2Entities()
            : base("name=Proyecto2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cajas> cajas { get; set; }
        public virtual DbSet<cajasxpersonas> cajasxpersonas { get; set; }
        public virtual DbSet<cajasxsucursales> cajasxsucursales { get; set; }
        public virtual DbSet<cantones> cantones { get; set; }
        public virtual DbSet<companias> companias { get; set; }
        public virtual DbSet<distritos> distritos { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<facturasxpersonas> facturasxpersonas { get; set; }
        public virtual DbSet<facturasxsucursales> facturasxsucursales { get; set; }
        public virtual DbSet<formapagos> formapagos { get; set; }
        public virtual DbSet<formapagosxfacturas> formapagosxfacturas { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<personasxdistritos> personasxdistritos { get; set; }
        public virtual DbSet<personasxsucursales> personasxsucursales { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<productosxfacturas> productosxfacturas { get; set; }
        public virtual DbSet<productosxproveedores> productosxproveedores { get; set; }
        public virtual DbSet<productosxsucursales> productosxsucursales { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<provincias> provincias { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<rolesxpersonas> rolesxpersonas { get; set; }
        public virtual DbSet<sucursales> sucursales { get; set; }
        public virtual DbSet<sucursalesxcompanias> sucursalesxcompanias { get; set; }
        public virtual DbSet<sucursalesxdistritos> sucursalesxdistritos { get; set; }
    }
}
