//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolesxpersonas
    {
        public int idcedula { get; set; }
        public int idrol { get; set; }
        public bool logicdelete { get; set; }
    
        public virtual personas personas { get; set; }
        public virtual roles roles { get; set; }
    }
}
