//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sucursales()
        {
            this.cajasxsucursales = new HashSet<cajasxsucursales>();
            this.facturasxsucursales = new HashSet<facturasxsucursales>();
            this.personasxsucursales = new HashSet<personasxsucursales>();
            this.productosxsucursales = new HashSet<productosxsucursales>();
            this.sucursalesxcompanias = new HashSet<sucursalesxcompanias>();
            this.sucursalesxdistritos = new HashSet<sucursalesxdistritos>();
        }
    
        public int idsucursal { get; set; }
        public string nombre { get; set; }
        public int iddireccion { get; set; }
        public bool logicdelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajasxsucursales> cajasxsucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturasxsucursales> facturasxsucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personasxsucursales> personasxsucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productosxsucursales> productosxsucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursalesxcompanias> sucursalesxcompanias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursalesxdistritos> sucursalesxdistritos { get; set; }
    }
}
