//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursalesxdistritos
    {
        public int idsucursal { get; set; }
        public int iddistrito { get; set; }
        public string direccion { get; set; }
        public bool logicdelete { get; set; }
    
        public virtual distritos distritos { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
